version: '3'

services:
  user-api:
    build:
      context: ./comedor-api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: comedor-api
    restart: unless-stopped
    ports:
      - "80:8080"
    networks:
      - my_network

  validations-api:
    build:
      context: ./validations-api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: validations-api
    restart: unless-stopped
    ports:
      - "81:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge