apiVersion: apps/v1
kind: Deployment
metadata:
  name: comedor-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comedor-api
  template:
    metadata:
      labels:
        app: comedor-api
    spec:
      containers:
        - name: comedor-api
          image: "058264457642.dkr.ecr.us-east-1.amazonaws.com/medio-curso:comedor-api"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret