apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuario-api
  template:
    metadata:
      labels:
        app: usuario-api
    spec:
      containers:
        - name: usuario-api
          image: "058264457642.dkr.ecr.us-east-1.amazonaws.com/medio-curso:usuario-api"
          ports:
            - containerPort: 8081
